# Generated by Django 4.2.14 on 2024-08-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
