# Generated by Django 4.2.14 on 2024-07-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionmonitoring',
            name='progress',
        ),
    ]
